name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Dieser fertige Roboter übernimmt den kompletten Build-Prozess fehlerfrei
      - name: Buildozer Action
        uses: ArtemGovorov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk
